# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radiobutton.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.country_box = QtWidgets.QGroupBox(self.centralwidget)
        self.country_box.setGeometry(QtCore.QRect(70, 80, 141, 231))
        self.country_box.setObjectName("country_box")
        self.gridLayoutWidget = QtWidgets.QWidget(self.country_box)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 101, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.england = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.england.setObjectName("england")
        self.gridLayout.addWidget(self.england, 1, 0, 1, 1)
        self.turkey = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.turkey.setObjectName("turkey")
        self.gridLayout.addWidget(self.turkey, 0, 0, 1, 1)
        self.france = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.france.setObjectName("france")
        self.gridLayout.addWidget(self.france, 3, 0, 1, 1)
        self.germany = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.germany.setObjectName("germany")
        self.gridLayout.addWidget(self.germany, 2, 0, 1, 1)
        self.job_group = QtWidgets.QGroupBox(self.centralwidget)
        self.job_group.setGeometry(QtCore.QRect(230, 80, 141, 231))
        self.job_group.setObjectName("job_group")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.job_group)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 101, 191))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.police = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.police.setObjectName("police")
        self.gridLayout_2.addWidget(self.police, 3, 0, 1, 1)
        self.carpenter = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.carpenter.setObjectName("carpenter")
        self.gridLayout_2.addWidget(self.carpenter, 0, 0, 1, 1)
        self.doctor = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.doctor.setObjectName("doctor")
        self.gridLayout_2.addWidget(self.doctor, 1, 0, 1, 1)
        self.teacher = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.teacher.setObjectName("teacher")
        self.gridLayout_2.addWidget(self.teacher, 2, 0, 1, 1)
        self.get_selected = QtWidgets.QPushButton(self.centralwidget)
        self.get_selected.setGeometry(QtCore.QRect(150, 330, 121, 51))
        self.get_selected.setObjectName("get_selected")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 390, 381, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.country_box.setTitle(_translate("MainWindow", "Country"))
        self.england.setText(_translate("MainWindow", "England"))
        self.turkey.setText(_translate("MainWindow", "Turkey"))
        self.france.setText(_translate("MainWindow", "France"))
        self.germany.setText(_translate("MainWindow", "Germany"))
        self.job_group.setTitle(_translate("MainWindow", "Job"))
        self.police.setText(_translate("MainWindow", "Police"))
        self.carpenter.setText(_translate("MainWindow", "Carpenter"))
        self.doctor.setText(_translate("MainWindow", "Doctor"))
        self.teacher.setText(_translate("MainWindow", "Teacher"))
        self.get_selected.setText(_translate("MainWindow", "Get"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
